In [1]:
import os
import pandas as pd
from tqdm.auto import tqdm

from dotenv import load_dotenv
load_dotenv()

True

In [2]:
BASE_FOLDER = os.path.join('..', 'data', 'info_collection')

os.listdir(BASE_FOLDER)

['class_10.jsonl',
 'class_11.jsonl',
 'class_12.jsonl',
 'class_6.jsonl',
 'class_7.jsonl',
 'class_8.jsonl',
 'class_9.jsonl',
 'cleaned_class_10.jsonl',
 'cleaned_class_11.jsonl',
 'cleaned_class_12.jsonl',
 'cleaned_class_6.jsonl',
 'cleaned_class_7.jsonl',
 'cleaned_class_8.jsonl',
 'cleaned_class_9.jsonl',
 'preprocess_input.jsonl']

In [17]:
class_6_df = pd.read_json(os.path.join(BASE_FOLDER, 'class_6.jsonl'), lines=True)
class_7_df = pd.read_json(os.path.join(BASE_FOLDER, 'class_7.jsonl'), lines=True)
class_8_df = pd.read_json(os.path.join(BASE_FOLDER, 'class_8.jsonl'), lines=True)
class_9_df = pd.read_json(os.path.join(BASE_FOLDER, 'class_9.jsonl'), lines=True)
class_10_df = pd.read_json(os.path.join(BASE_FOLDER, 'class_10.jsonl'), lines=True)
class_11_df = pd.read_json(os.path.join(BASE_FOLDER, 'class_11.jsonl'), lines=True)
class_12_df = pd.read_json(os.path.join(BASE_FOLDER, 'class_12.jsonl'), lines=True)

In [18]:
class_6_df.head()

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept
0,6,1,Knowing Our Numbers,1.1,Q 1. (a),[1 lakh = ______ ten thousand.],"[[1 lakh = 10 ten thousand., Explanation:, 1 l...",Larger Number of Digits 7 and Above
1,6,1,Knowing Our Numbers,1.1,Q 1. (b),[1 million = ______ hundred thousand.],"[[1 million = 10 hundred thousand., Explanatio...",Larger Number of Digits 7 and Above
2,6,1,Knowing Our Numbers,1.1,Q 1. (c),[1 crore = ______ ten lakh.],"[[1 crore = 10 ten lakh., Explanation:, 1 cror...",Larger Number of Digits 7 and Above
3,6,1,Knowing Our Numbers,1.1,Q 1. (d),[1 crore = ______ million.],"[[1 crore = 10 million., Explanation:, 1 crore...",Larger Number of Digits 7 and Above
4,6,1,Knowing Our Numbers,1.1,Q 1. (e),[1 million = ______ lakh.],"[[1 million = 10 lakh., Explanation:, 1 millio...",Larger Number of Digits 7 and Above

## Clean Class 6

In [19]:
class_6_df = class_6_df[~((class_6_df['problem'].apply(lambda x: x == [])) | (class_6_df['solution'].apply(lambda x: x == [] or x==[['']] or x==[[]])))].reset_index(drop=True)
class_6_df['drop'] = False
class_6_df.chapter_name.value_counts()

chapter_name
Playing with Numbers               145
Fractions                          135
Decimals                           135
Understanding Elementary Shapes    130
Algebra                             85
Integers                            73
Ratio and Proportion                67
Basic Geometrical Ideas             62
Whole Numbers                       59
Mensuration                         58
Knowing Our Numbers                 48
Practical Geometry                  35
Data Handling                       17
Symmetry                             5
Name: count, dtype: int64

In [20]:
chapter_name = 'Symmetry'
class_6_df[class_6_df['chapter_name'] == chapter_name].concept.unique().tolist()

['Concept of Symmetry']

In [21]:
idx = 0
selected_concept = class_6_df[class_6_df['chapter_name'] == chapter_name].concept.unique().tolist()[idx]
print(selected_concept)
class_6_df[class_6_df['concept'] == selected_concept]

Concept of Symmetry

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept,drop
1014,6,13,Symmetry,13.1,Q 1.,[List any four symmetrical objects from your h...,"[[Paper sheet, Glass, CD, Bucket]]",Concept of Symmetry,False
1015,6,13,Symmetry,13.1,Q 2.,"[For the given figure, which one is the mirror...",[[Line l2 is the mirror line of this figure. T...,Concept of Symmetry,False
1016,6,13,Symmetry,13.1,Q 3. (a),[Identify the shape given below. Check whether...,"[[Yes, it is symmetric., The figure given belo...",Concept of Symmetry,False
1017,6,13,Symmetry,13.1,Q 3. (b),[Identify the shape given below. Check whether...,"[[Yes, it is symmetric., The figure given belo...",Concept of Symmetry,False
1018,6,13,Symmetry,13.1,Q 3. (c),[Identify the shape given below. Check whether...,"[[No, this figure is not symmetric.]]",Concept of Symmetry,False

In [22]:
concepts_to_drop_from_class_6 = [
    'Fraction on the Number Line',
    'Concept of Fractions',
    'Concept of Decimal Numbers',
    'The Idea of a Variable',
    'Addition of Integers on Number line',
    'Concept of Area'
]

chapter_to_drop_from_class_6 =[
    'Understanding Elementary Shapes',
    'Basic Geometrical Ideas',
    'Knowing Our Numbers',
    'Practical Geometry',
    'Data Handling',
    'Symmetry'
]

keywords_to_drop_from_class_6 = [
    'diagram',
    'fig',
    'number line',
]

In [23]:
class_6_df['drop'] = class_6_df['drop'] | class_6_df['concept'].apply(lambda x: x in concepts_to_drop_from_class_6)
class_6_df['drop'] = class_6_df['drop'] | class_6_df['chapter_name'].apply(lambda x: x in chapter_to_drop_from_class_6)
class_6_df['drop'] = class_6_df['drop'] | class_6_df['problem'].apply(lambda x: any([keyword in x for keyword in keywords_to_drop_from_class_6]))

In [24]:
class_6_df = class_6_df[~class_6_df['drop']].reset_index(drop=True)
class_6_df.drop(columns='drop', inplace=True)
class_6_df.to_json(os.path.join(BASE_FOLDER, 'cleaned_class_6.jsonl'), index=False, lines=True, orient='records')

## Clean Class 7

In [25]:
class_7_df = class_7_df[~((class_7_df['problem'].apply(lambda x: x == [])) | (class_7_df['solution'].apply(lambda x: x == [] or x==[['']] or x==[[]])))].reset_index(drop=True)
class_7_df['drop'] = False
class_7_df.chapter_name.value_counts()

chapter_name
Fractions and Decimals             191
Algebraic Expressions              108
Simple Equations                   105
Exponents and Powers                90
Integers                            85
Symmetry                            68
Rational Numbers                    64
Perimeter and Area                  58
Comparing Quantities                52
Lines and Angles                    42
The Triangle and its Properties     41
Data Handling                       32
Visualising Solid Shapes            31
Congruence of Triangles             24
Practical Geometry                  16
Name: count, dtype: int64

In [26]:
chapter_name = 'Practical Geometry'
class_7_df[class_7_df['chapter_name'] == chapter_name].concept.unique().tolist()

['Construction of a Line Parallel to a Given Line, Through a Point Not on the Line',
 'Construction of Triangles - Constructing a Triangle When the Length of Its Three Sides Are Known (SSS Criterion)',
 'Construction of Triangles - Constructing a Triangle When the Lengths of Two Sides and the Measure of the Angle Between Them Are Known. (SAS Criterion)',
 'Construction of Triangles - Constructing a Triangle When the Measures of Two of Its Angles and the Length of the Side Included Between Them is Given. (ASA Criterion)',
 'Construction of Triangles - Constructing a Right-angled Triangle When the Length of One Leg and Its Hypotenuse Are Given (RHS Criterion)']

In [27]:
idx = 3
selected_concept = class_7_df[class_7_df['chapter_name'] == chapter_name].concept.unique().tolist()[idx]
print(selected_concept)
class_7_df[class_7_df['concept'] == selected_concept]

Construction of Triangles - Constructing a Triangle When the Measures of Two of Its Angles and the Length of the Side Included Between Them is Given. (ASA Criterion)

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept,drop
646,7,10,Practical Geometry,10.4,Q 1,"[Construct ΔABC, given m∠A = 60°, m∠B = 30° an...",[[A rough sketch of the required ΔABC is as fo...,Construction of Triangles - Constructing a Tri...,False
647,7,10,Practical Geometry,10.4,Q 2,"[Construct ΔPQR if PQ = 5 cm, m∠PQR = 105° and...",[[A rough sketch of the required ΔPQR is as fo...,Construction of Triangles - Constructing a Tri...,False
648,7,10,Practical Geometry,10.4,Q 3,[Examine whether you can construct ΔDEF such t...,"[[Given that,, m∠E = 110° and m∠F = 80°, There...",Construction of Triangles - Constructing a Tri...,False

In [28]:
concepts_to_drop_from_class_7 = [
    'Concept of Exponents',
    'Organisation of Data',
    'Concept of Bar Graph',
]

chapter_to_drop_from_class_7 =[
    'Symmetry',
    'Lines and Angles',
    'The Triangle and its Properties',
    'Visualising Solid Shapes',
    'Practical Geometry',
]

keywords_to_drop_from_class_7 = [
    'diagram',
    'fig',
    'number line',
    'table',
    'draw',
    'construct',
]

In [29]:
class_7_df['drop'] = class_7_df['drop'] | class_7_df['concept'].apply(lambda x: x in concepts_to_drop_from_class_7)
class_7_df['drop'] = class_7_df['drop'] | class_7_df['chapter_name'].apply(lambda x: x in chapter_to_drop_from_class_7)
class_7_df['drop'] = class_7_df['drop'] | class_7_df['problem'].apply(lambda x: any([keyword.lower() in str(x).lower() for keyword in keywords_to_drop_from_class_7]))

In [30]:
class_7_df = class_7_df[~class_7_df['drop']].reset_index(drop=True)
class_7_df.drop(columns='drop', inplace=True)
class_7_df.to_json(os.path.join(BASE_FOLDER, 'cleaned_class_7.jsonl'), index=False, lines=True, orient='records')

In [246]:
class_7_df.shape

(699, 8)

## Clean Class 8

In [31]:
class_8_df = class_8_df[~((class_8_df['problem'].apply(lambda x: x == [])) | (class_8_df['solution'].apply(lambda x: x == [] or x==[['']] or x==[[]] or x==[[""], [""]])))].reset_index(drop=True)
class_8_df['drop'] = False
class_8_df.chapter_name.value_counts()

chapter_name
Squares and Square Roots                108
Algebraic Expressions and Identities    107
Factorisation                           105
Linear Equations in One Variable         63
Understanding Quadrilaterals             61
Comparing Quantities                     37
Mensuration                              34
Exponents and Powers                     33
Cubes and Cube Roots                     32
Rational Numbers                         31
Direct and Inverse Proportions           25
Name: count, dtype: int64

In [32]:
chapter_name = 'Direct and Inverse Proportions'
class_8_df[class_8_df['chapter_name'] == chapter_name].concept.unique().tolist()

['Concept of Direct Proportion', 'Concept of Inverse Proportion']

In [33]:
idx = -2
selected_concept = class_8_df[class_8_df['chapter_name'] == chapter_name].concept.unique().tolist()[idx]
print(selected_concept)
class_8_df[class_8_df['concept'] == selected_concept]

Concept of Direct Proportion

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept,drop
506,8,13,Direct and Inverse Proportions,13.1,Q 1,[Following are the car parking charges near a ...,"[[Since, `1/15 ne 2/25 ne3/35 ne 2/15`, ∴ The ...",Concept of Direct Proportion,False
507,8,13,Direct and Inverse Proportions,13.1,Q 3,"[In Question 2 above, if 1 part of a red pigme...",[[Let the parts of red pigment required to mix...,Concept of Direct Proportion,False
508,8,13,Direct and Inverse Proportions,13.1,Q 4,[A machine in a soft drink factory fills 840 b...,[[Let the number of bottles filled by the mach...,Concept of Direct Proportion,False
509,8,13,Direct and Inverse Proportions,13.1,Q 5,"[A photograph of a bacteria enlarged 50,000 ti...",[[Let the actual length of bacteria be x cm an...,Concept of Direct Proportion,False
510,8,13,Direct and Inverse Proportions,13.1,Q 6,"[In a model of a ship, the mast is 9 cm high, ...",[[Let the length of the mast of the model ship...,Concept of Direct Proportion,False
511,8,13,Direct and Inverse Proportions,13.1,Q 7,[Suppose 2 kg of sugar contains 9 × 106 crysta...,[[i) Let the number of sugar crystals in 5 kg ...,Concept of Direct Proportion,False
512,8,13,Direct and Inverse Proportions,13.1,Q 8,[Rashmi has a road map with a scale of 1 cm re...,[[Let the distance represented on the map be x...,Concept of Direct Proportion,False
513,8,13,Direct and Inverse Proportions,13.1,Q 8,[Rashmi has a road map with a scale of 1 cm re...,[[Let the distance represented on the map be x...,Concept of Direct Proportion,False
514,8,13,Direct and Inverse Proportions,13.1,Q 9.1,[A 5 m 60 cm high vertical pole casts a shadow...,[[Let the length of the shadow of the other po...,Concept of Direct Proportion,False
515,8,13,Direct and Inverse Proportions,13.1,Q 9.2,[A 5 m 60 cm high vertical pole casts a shadow...,"[[Given, length of shadow of 5 m 60 cm high ve...",Concept of Direct Proportion,False
516,8,13,Direct and Inverse Proportions,13.1,Q 10,[A loaded truck travels 14 km in 25 minutes. I...,[[Let the distance travelled by the truck in 5...,Concept of Direct Proportion,False

In [34]:
concepts_to_drop_from_class_8 = [
    'Rational Numbers on a Number Line',
]

chapter_to_drop_from_class_8 =[
    'Understanding Quadrilaterals',
]

keywords_to_drop_from_class_8 = [
    'diagram',
    'fig',
    'number line',
    'table',
    'draw',
    'construct',
]

In [35]:
class_8_df['drop'] = class_8_df['drop'] | class_8_df['concept'].apply(lambda x: x in concepts_to_drop_from_class_8)
class_8_df['drop'] = class_8_df['drop'] | class_8_df['chapter_name'].apply(lambda x: x in chapter_to_drop_from_class_8)
class_8_df['drop'] = class_8_df['drop'] | class_8_df['problem'].apply(lambda x: any([keyword.lower() in str(x).lower() for keyword in keywords_to_drop_from_class_8]))

In [36]:
class_8_df = class_8_df[~class_8_df['drop']].reset_index(drop=True)
class_8_df.drop(columns='drop', inplace=True)
class_8_df.to_json(os.path.join(BASE_FOLDER, 'cleaned_class_8.jsonl'), index=False, lines=True, orient='records')

In [37]:
class_8_df.shape

(547, 8)

## Clean Class 9

In [38]:
class_9_df = class_9_df[~((class_9_df['problem'].apply(lambda x: x == [])) | (class_9_df['solution'].apply(lambda x: x == [] or x==[['']] or x==[[]] or x==[[""], [""]])))].reset_index(drop=True)
class_9_df['drop'] = False
class_9_df.chapter_name.value_counts()

chapter_name
Polynomials                              113
Number Systems                            57
Circles                                   44
Surface Area and Volumes                  35
Linear Equations in two Variables         34
Triangles                                 31
Areas of Parallelograms and Triangles     31
Statistics                                26
Quadrilaterals                            19
Introduction to Euclid's Geometry         17
Lines and Angles                          17
Coordinate Geometry                       15
Heron's Formula                           15
Constructions                             14
Probability                               11
Name: count, dtype: int64

In [39]:
chapter_name = 'Probability'
class_9_df[class_9_df['chapter_name'] == chapter_name].concept.unique().tolist()

['Probability - an Experimental Approach']

In [40]:
idx = 0
selected_concept = class_9_df[class_9_df['chapter_name'] == chapter_name].concept.unique().tolist()[idx]
print(selected_concept)
class_9_df[class_9_df['concept'] == selected_concept]

Probability - an Experimental Approach

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept,drop
468,9,15,Probability,15.1,Q 1,"[In a cricket match, a batswoman hits a bounda...",[[Number of times the batswoman hits a boundar...,Probability - an Experimental Approach,False
469,9,15,Probability,15.1,Q 2,[1500 families with 2 children were selected r...,"[[Total number of families = 475 + 814 + 211, ...",Probability - an Experimental Approach,False
470,9,15,Probability,15.1,Q 3,"[In a particular section of Class IX, 40 stude...",[[Number of students born in the month of Augu...,Probability - an Experimental Approach,False
471,9,15,Probability,15.1,Q 4,[Three coins are tossed simultaneously 200 tim...,"[[Number of times 2 heads come up = 72, Total ...",Probability - an Experimental Approach,False
472,9,15,Probability,15.1,Q 5,[An organization selected 2400 families at ran...,[[Number of total families surveyed = 10 + 160...,Probability - an Experimental Approach,False
473,9,15,Probability,15.1,Q 6,[A teacher wanted to analyse the performance o...,"[[Totalnumber of students = 90, (i) Number of ...",Probability - an Experimental Approach,False
474,9,15,Probability,15.1,Q 7,[To know the opinion of the students about the...,"[[Total number of students = 135 + 65 = 200, (...",Probability - an Experimental Approach,False
475,9,15,Probability,15.1,Q 8,[The distance (in km) of 40 engineers from the...,"[[(i) Total number of engineers = 40, Number o...",Probability - an Experimental Approach,False
476,9,15,Probability,15.1,Q 11,"[Eleven bags of wheat flour, each marked 5 kg,...","[[Number of total bags = 11, Number of bags co...",Probability - an Experimental Approach,False
477,9,15,Probability,15.1,Q 12,[The above frequency distribution table repres...,[[Number days for which the concentration of s...,Probability - an Experimental Approach,False
478,9,15,Probability,15.1,Q 13,[The above frequency distribution table repres...,[[Number of students having blood group AB = 3...,Probability - an Experimental Approach,False

In [41]:
concepts_to_drop_from_class_9 = [
    'Graph of a Linear Equation in Two Variables',
    'Graphical Representation of Data',
    'Cartesian Coordinate System',
    'Plotting a Point in the Plane If Its Coordinates Are Given.',
]

chapter_to_drop_from_class_9 =[
    'Constructions',
]

keywords_to_drop_from_class_9 = [
    'diagram',
    'fig',
    'number line',
    'table',
    'draw',
    'construct',
]

In [42]:
class_9_df['drop'] = class_9_df['drop'] | class_9_df['concept'].apply(lambda x: x in concepts_to_drop_from_class_9)
class_9_df['drop'] = class_9_df['drop'] | class_9_df['chapter_name'].apply(lambda x: x in chapter_to_drop_from_class_9)
class_9_df['drop'] = class_9_df['drop'] | class_9_df['problem'].apply(lambda x: any([keyword.lower() in str(x).lower() for keyword in keywords_to_drop_from_class_9]))

In [43]:
class_9_df = class_9_df[~class_9_df['drop']].reset_index(drop=True)
class_9_df.drop(columns='drop', inplace=True)
class_9_df.to_json(os.path.join(BASE_FOLDER, 'cleaned_class_9.jsonl'), index=False, lines=True, orient='records')

In [44]:
class_9_df.shape

(311, 8)

## Clean Class 10

In [45]:
class_10_df = class_10_df[~((class_10_df['problem'].apply(lambda x: x == [])) | (class_10_df['solution'].apply(lambda x: x == [] or x==[['']] or x==[[]] or x==[[""], [""]])))].reset_index(drop=True)
class_10_df['drop'] = False
class_10_df.chapter_name.value_counts()

chapter_name
Arithmetic Progressions                      94
Triangles                                    84
Pair of Linear Equations in Two Variables    72
Introduction to Trigonometry                 60
Real Numbers                                 50
Quadratic Equations                          49
Probability                                  48
Coordinate Geometry                          39
Surface Areas and Volumes                    37
Areas Related to Circles                     36
Polynomials                                  35
Statistics                                   25
Circles                                      19
Some Applications of Trigonometry            15
Name: count, dtype: int64

In [46]:
chapter_name = 'Some Applications of Trigonometry'
class_10_df[class_10_df['chapter_name'] == chapter_name].concept.unique().tolist()

['Heights and Distances']

In [47]:
idx = 0
selected_concept = class_10_df[class_10_df['chapter_name'] == chapter_name].concept.unique().tolist()[idx]
print(selected_concept)
class_10_df[class_10_df['concept'] == selected_concept]

Heights and Distances

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept,drop
483,10,9,Some Applications of Trigonometry,9.1,Q 1,"[A circus artist is climbing a 20 m long rope,...",[[It can be observed from the figure that AB i...,Heights and Distances,False
484,10,9,Some Applications of Trigonometry,9.1,Q 2,[A tree breaks due to storm and the broken par...,"[[, Let AC was the original tree. Due to storm...",Heights and Distances,False
485,10,9,Some Applications of Trigonometry,9.1,Q 3,[A contractor plans to install two slides for ...,[[It can be observed that AC and PR are the sl...,Heights and Distances,False
486,10,9,Some Applications of Trigonometry,9.1,Q 5,[A kite is flying at a height of 60 m above th...,"[[, Let K be the kite and the string is tied t...",Heights and Distances,False
487,10,9,Some Applications of Trigonometry,9.1,Q 6,[A 1.5 m tall boy is standing at some distance...,"[[, Let the boy stand at point S initially. He...",Heights and Distances,False
488,10,9,Some Applications of Trigonometry,9.1,Q 7,"[From a point on the ground, the angles of ele...","[[, Let AB be the building of height 20 m and ...",Heights and Distances,False
489,10,9,Some Applications of Trigonometry,9.1,Q 8,"[A statue, 1.6 m tall, stands on a top of pede...","[[, Let AB be the statue, BC be the pedestal, ...",Heights and Distances,False
490,10,9,Some Applications of Trigonometry,9.1,Q 9,[The angle of elevation of the top of a buildi...,"[[, Let AB be the building and CD be the tower...",Heights and Distances,False
491,10,9,Some Applications of Trigonometry,9.1,Q 10,[Two poles of equal heights are standing oppos...,"[[, Let AB and CD be the poles and O is the po...",Heights and Distances,False
492,10,9,Some Applications of Trigonometry,9.1,Q 11,[A TV tower stands vertically on a bank of a c...,"[[In ΔABC,, \frac{A B}{B C} = tan 60º, \frac{A...",Heights and Distances,False
493,10,9,Some Applications of Trigonometry,9.1,Q 12,"[From the top of a 7 m high building, the angl...","[[, Let AB be a building and CD be a cable tow...",Heights and Distances,False
494,10,9,Some Applications of Trigonometry,9.1,Q 13,[As observed from the top of a 75 m high light...,"[[, Let AB be the lighthouse and the two ships...",Heights and Distances,False
495,10,9,Some Applications of Trigonometry,9.1,Q 14,[A 1.2 m tall girl spots a balloon moving with...,"[[, Let the initial position A of balloon chan...",Heights and Distances,False
496,10,9,Some Applications of Trigonometry,9.1,Q 15,[A straight highway leads to the foot of a tow...,"[[, Let AB be the tower., Initial position of ...",Heights and Distances,False
497,10,9,Some Applications of Trigonometry,9.1,Q 16,[The angles of elevation of the top of a tower...,"[[, Let AQ be the tower and R, S are the point...",Heights and Distances,False

In [48]:
concepts_to_drop_from_class_10 = [
    'Graphical Method of Solution of a Pair of Linear Equations',
    'Areas of Combinations of Plane Figures',
    'Graphical Representation of Cumulative Frequency Distribution',
    
]

chapter_to_drop_from_class_10 =[
    'Geometrical Meaning of the Zeroes of a Polynomial',
    'Statistics',
]

keywords_to_drop_from_class_10 = [
    'diagram',
    'fig',
    'number line',
    'table',
    'draw',
    'construct',
]

In [49]:
class_10_df['drop'] = class_10_df['drop'] | class_10_df['concept'].apply(lambda x: x in concepts_to_drop_from_class_10)
class_10_df['drop'] = class_10_df['drop'] | class_10_df['chapter_name'].apply(lambda x: x in chapter_to_drop_from_class_10)
class_10_df['drop'] = class_10_df['drop'] | class_10_df['problem'].apply(lambda x: any([keyword.lower() in str(x).lower() for keyword in keywords_to_drop_from_class_10]))

In [50]:
class_10_df = class_10_df[~class_10_df['drop']].reset_index(drop=True)
class_10_df.drop(columns='drop', inplace=True)
class_10_df.to_json(os.path.join(BASE_FOLDER, 'cleaned_class_10.jsonl'), index=False, lines=True, orient='records')

In [51]:
class_10_df.shape

(506, 8)

## Clean Class 11

In [52]:
class_11_df = class_11_df[~((class_11_df['problem'].apply(lambda x: x == [])) | (class_11_df['solution'].apply(lambda x: x == [] or x==[['']] or x==[[]] or x==[[""], [""]])))].reset_index(drop=True)
class_11_df['drop'] = False
class_11_df.chapter_name.value_counts()

chapter_name
Sets                                          150
Straight Lines                                 75
Mathematical Reasoning                         70
Linear Inequalities                            67
Trigonometric Functions                        60
Probability                                    53
Permutations and Combinations                  49
Complex Numbers and Quadratic Equations        46
Conic Sections                                 44
Limits and Derivatives                         37
Statistics                                     30
Introduction to Three Dimensional Geometry     26
Principle of Mathematical Induction            24
Name: count, dtype: int64

In [53]:
chapter_name = 'Introduction to Three Dimensional Geometry'
class_11_df[class_11_df['chapter_name'] == chapter_name].concept.unique().tolist()

['Three - Dimensional Geometry - Coordinates of a Point in Space',
 'Three - Dimensional Geometry - Coordinate Axes and Coordinate  planes',
 'Three - Dimensional Geometry - Distance Between Two Points',
 'Three - Dimensional Geometry - Section Formula']

In [54]:
idx = 0
selected_concept = class_11_df[class_11_df['chapter_name'] == chapter_name].concept.unique().tolist()[idx]
print(selected_concept)
class_11_df[class_11_df['concept'] == selected_concept]

Three - Dimensional Geometry - Coordinates of a Point in Space

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept,drop
515,11,12,Introduction to Three Dimensional Geometry,12.1,Q 1,[A point is on the x-axis. What are its y-coor...,"[[If a point is on the x-axis, then its y-coor...",Three - Dimensional Geometry - Coordinates of ...,False
516,11,12,Introduction to Three Dimensional Geometry,12.1,Q 2,[A point is in the XZ-plane. What can you say ...,"[[If a point is in the XZ plane, then its y-co...",Three - Dimensional Geometry - Coordinates of ...,False
519,11,12,Introduction to Three Dimensional Geometry,12.1,Q 4.2,[Fill in the blanks: The coordinates of points...,[[The coordinates of points in the XY-plane ar...,Three - Dimensional Geometry - Coordinates of ...,False
536,11,12,Introduction to Three Dimensional Geometry,Error,Q 2,[Find the lengths of the medians of the triang...,"[[Let AD, BE, and CF be the medians of the giv...",Three - Dimensional Geometry - Coordinates of ...,False
538,11,12,Introduction to Three Dimensional Geometry,Error,Q 4,[Find the coordinates of a point on y-axis whi...,"[[If a point is on the y-axis, then x-coordina...",Three - Dimensional Geometry - Coordinates of ...,False
539,11,12,Introduction to Three Dimensional Geometry,Error,Q 5,[A point R with x-coordinate 4 lies on the lin...,[[The coordinates of points P and Q are given ...,Three - Dimensional Geometry - Coordinates of ...,False
540,11,12,Introduction to Three Dimensional Geometry,Error,Q 6,"[If A and B be the points (3, 4, 5) and (–1, 3...",[[The coordinates of points A and B are given ...,Three - Dimensional Geometry - Coordinates of ...,False

In [55]:
concepts_to_drop_from_class_11 = [
    'Venn Diagrams',
    'Graphical Solution of Linear Inequalities in Two Variables',
    
]

chapter_to_drop_from_class_11 =[
    
]

keywords_to_drop_from_class_11 = [
    'diagram',
    'fig',
    'number line',
    'table',
    'draw',
    'construct',
]

In [56]:
class_11_df['drop'] = class_11_df['drop'] | class_11_df['concept'].apply(lambda x: x in concepts_to_drop_from_class_11)
class_11_df['drop'] = class_11_df['drop'] | class_11_df['chapter_name'].apply(lambda x: x in chapter_to_drop_from_class_11)
class_11_df['drop'] = class_11_df['drop'] | class_11_df['problem'].apply(lambda x: any([keyword.lower() in str(x).lower() for keyword in keywords_to_drop_from_class_11]))

In [58]:
class_11_df = class_11_df[~class_11_df['drop']].reset_index(drop=True)
class_11_df.drop(columns='drop', inplace=True)
class_11_df.to_json(os.path.join(BASE_FOLDER, 'cleaned_class_11.jsonl'), index=False, lines=True, orient='records')

In [370]:
class_11_df.shape

(698, 8)

## Clean Class 12

In [59]:
class_12_df = class_12_df[~((class_12_df['problem'].apply(lambda x: x == [])) | (class_12_df['solution'].apply(lambda x: x == [] or x==[['']] or x==[[]] or x==[[""], [""]])))].reset_index(drop=True)
class_12_df['drop'] = False
class_12_df.chapter_name.value_counts()

chapter_name
Application of Derivatives          125
Probability                         111
Differential Equations              103
Continuity and Differentiability    103
Matrices                             86
Three Dimensional Geometry           74
Relations and Functions              69
Vector Algebra                       66
Determinants                         56
Inverse Trigonometric Functions      51
Application of Integrals             38
Linear Programming                   30
Integrals                             7
Name: count, dtype: int64

In [60]:
chapter_name = 'Linear Programming'
class_12_df[class_12_df['chapter_name'] == chapter_name].concept.unique().tolist()

['Linear Programming Problem and Its Mathematical Formulation',
 'Different Types of Linear Programming Problems']

In [61]:
idx = 0
selected_concept = class_12_df[class_12_df['chapter_name'] == chapter_name].concept.unique().tolist()[idx]
print(selected_concept)
class_12_df[class_12_df['concept'] == selected_concept]

Linear Programming Problem and Its Mathematical Formulation

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept,drop
778,12,12,Linear Programming,12.1,Q 1,[Solve the following Linear Programming Proble...,[[The feasible region determined by the constr...,Linear Programming Problem and Its Mathematica...,False
779,12,12,Linear Programming,12.1,Q 2,[Solve the following Linear Programming Proble...,[[The feasible region determined by the system...,Linear Programming Problem and Its Mathematica...,False
780,12,12,Linear Programming,12.1,Q 3,[Solve the following Linear Programming Proble...,[[The feasible region determined by the system...,Linear Programming Problem and Its Mathematica...,False
781,12,12,Linear Programming,12.1,Q 4,[Solve the following Linear Programming Proble...,[[The feasible region determined by the system...,Linear Programming Problem and Its Mathematica...,False
782,12,12,Linear Programming,12.1,Q 5,[Solve the following Linear Programming Proble...,[[The feasible region determined by the constr...,Linear Programming Problem and Its Mathematica...,False
783,12,12,Linear Programming,12.1,Q 6,[Solve the following Linear Programming Proble...,[[The feasible region determined by the constr...,Linear Programming Problem and Its Mathematica...,False
784,12,12,Linear Programming,12.1,Q 7,[Show that the minimum of Z occurs at more tha...,[[The feasible region determined by the constr...,Linear Programming Problem and Its Mathematica...,False
785,12,12,Linear Programming,12.1,Q 9,[Show that the minimum of Z occurs at more tha...,[[The feasible region determined by the constr...,Linear Programming Problem and Its Mathematica...,False
786,12,12,Linear Programming,12.1,Q 10,[Show that the minimum of Z occurs at more tha...,"[[The region determined by the constraints, x ...",Linear Programming Problem and Its Mathematica...,False
787,12,12,Linear Programming,12.2,Q 1,[Refer to Example 9. How many packets of each ...,[[Let the diet contain x and y packets of food...,Linear Programming Problem and Its Mathematica...,False
790,12,12,Linear Programming,12.2,Q 2,[A farmer mixes two brands P and Q of cattle f...,[[Let the farmer mix x bags of brand P and y b...,Linear Programming Problem and Its Mathematica...,False
800,12,12,Linear Programming,12.3,Q 3,[A dietician wishes to mix together two kinds ...,[[Let the mixture contain x kg of food X and y...,Linear Programming Problem and Its Mathematica...,False
801,12,12,Linear Programming,12.3,Q 4,[A manufacturer makes two types of toys A and ...,[[Let x and y toys of type A and type B respec...,Linear Programming Problem and Its Mathematica...,False
802,12,12,Linear Programming,12.3,Q 5,[An aeroplane can carry a maximum of 200 passe...,[[Let the airline sell x tickets of executive ...,Linear Programming Problem and Its Mathematica...,False

In [62]:
concepts_to_drop_from_class_12 = [    

]

chapter_to_drop_from_class_12 = [
    
]

keywords_to_drop_from_class_12 = [
    'diagram',
    'fig',
    'number line',
    'table',
    'draw',
    'construct',
]

In [63]:
class_12_df['drop'] = class_12_df['drop'] | class_12_df['concept'].apply(lambda x: x in concepts_to_drop_from_class_12)
class_12_df['drop'] = class_12_df['drop'] | class_12_df['chapter_name'].apply(lambda x: x in chapter_to_drop_from_class_12)
class_12_df['drop'] = class_12_df['drop'] | class_12_df['problem'].apply(lambda x: any([keyword.lower() in str(x).lower() for keyword in keywords_to_drop_from_class_12]))

In [64]:
class_12_df = class_12_df[~class_12_df['drop']].reset_index(drop=True)
class_12_df.drop(columns='drop', inplace=True)
class_12_df.to_json(os.path.join(BASE_FOLDER, 'cleaned_class_12.jsonl'), index=False, lines=True, orient='records')

In [65]:
class_12_df.shape

(887, 8)

## Token Counting

In [61]:
import tiktoken
def get_tokens_openai(input_text, model="gpt-3.5-turbo-0613"):
    """Return the number of tokens used by a list of messages."""
    encoding = tiktoken.encoding_for_model(model)
    tokens_per_message = 3
    return tokens_per_message + len(encoding.encode(input_text)) + 3

In [51]:
problems = class_6_df['problem'].tolist() + class_7_df['problem'].tolist() + class_8_df['problem'].tolist() + class_9_df['problem'].tolist() + class_10_df['problem'].tolist() + class_11_df['problem'].tolist() + class_12_df['problem'].tolist()

solutions = class_6_df['solution'].tolist() + class_7_df['solution'].tolist() + class_8_df['solution'].tolist() + class_9_df['solution'].tolist() + class_10_df['solution'].tolist() + class_11_df['solution'].tolist() + class_12_df['solution'].tolist()

In [52]:
len(problems), len(solutions)

(5512, 5512)

In [65]:
prob_token_counts = []
for problem in tqdm(problems):
    # try:
    #     prob_token_counts.append(num_tokens_from_messages(problem))
    # except AttributeError:
    #     print(problem[0])
    #     break
    prob_token_counts.append(get_tokens_openai(problem[0]))

  0%|          | 0/5512 [00:00<?, ?it/s]

In [79]:
max(prob_token_counts), min(prob_token_counts), sum(prob_token_counts) / len(prob_token_counts), sum(prob_token_counts)

(235, 6, 37.82402031930334, 208486)

In [77]:
sol_token_counts = []
for sol in tqdm(solutions):
    sol_token_counts.append(get_tokens_openai("\n".join(["\n".join(sol[idx]) for idx in range(len(sol))])))

  0%|          | 0/5512 [00:00<?, ?it/s]

In [80]:
max(sol_token_counts), min(sol_token_counts), sum(sol_token_counts) / len(sol_token_counts), sum(sol_token_counts)

(1964, 6, 116.19339622641509, 640458)

In [81]:
208486 + 640458

848944

## New Section

In [3]:
sys_prompt = """You are a math professor who is very rigorous in writing down solutions. You also care about your students and write solution walkthrough in step-by-step manner and using latex everywhere necessary.

You will be given a math problem and its solution, you job is to re-write the problem in good latex and solution in very step-by-step manner for your students.
If you can find an efficient solution than given, please give that solution.

The output has to be in the YAML format:
```
to_drop: BOOLEAN
problem: "PROBLEM RE-WRITTEN IN PROPER LATEX"
solution:
  - "SOLUTION RE-WRITTEN IN PROPER LATEX IN MULTIPLE STEPS AS A LIST"
```
You should drop a problem altogether if its incomplete or problem has includes a diagram or is about constructing one or the problem is MCQ.
Keep the number of steps as minimum as possible.

Study the given solution, if you can solve the problem with a more efficient solution give that.
Combine latex commands in single step, not multiple.

DO NOT USE `\\begin{align*}` `\\begin{align}` `\\begin{aligned}` or any kind of other alignment in latex code.
Take care that you use right YAML format, do not nest steps!
"""

In [4]:
input_prompt = """<math_problem>
{math_problem}
</math_problem>

<solution>
{solution}
</solution>"""

In [5]:
var_df = pd.read_json(os.path.join(BASE_FOLDER, 'cleaned_class_6.jsonl'), lines=True)
var_df

,class,chapter_number,chapter_name,exercise_number,question_number,problem,solution,concept,exp_id
0,6,2,Whole Numbers,2.1,Q 1.,[Write the next three natural numbers after 10...,"[[10,999+1 = 11,000, 11,000 + 1 = 11,001, 11,0...",Concept for Natural Numbers,Exp0000
1,6,2,Whole Numbers,2.1,Q 2.,[Write the three whole numbers occurring just ...,[[Three whole numbers occurring just before 10...,Concept for Whole Numbers,Exp0001
2,6,2,Whole Numbers,2.1,Q 3.,[Which is the smallest whole number?],[[0 (zero) is the smallest whole number. All t...,Concept for Whole Numbers,Exp0002
3,6,2,Whole Numbers,2.1,Q 4.,[How many whole numbers are there between 32 a...,[[Whole numbers between 32 and 53 = 20 (53 − 3...,Concept for Whole Numbers,Exp0003
4,6,2,Whole Numbers,2.1,Q 5. (a),[Write the successor of 2440701.],"[[The successor of 2440701 is, 2440701 + 1 = 2...",Successor and Predecessor of Whole Number,Exp0004
...,...,...,...,...,...,...,...,...,...
673,6,12,Ratio and Proportion,12.3,Q 7.,[Cost of 4 dozens bananas is Rs 180. How many ...,[[Numbers of bananas bought in Rs 180 = 4 doze...,Concept of Unitary Method,Exp0673
674,6,12,Ratio and Proportion,12.3,Q 8.,[The weight of 72 books is 9 kg. What is the w...,"[[Weight of 72 books = 9 kg, Weight of 1 book ...",Concept of Unitary Method,Exp0674
675,6,12,Ratio and Proportion,12.3,Q 9.,[A truck requires 108 litres of diesel for cov...,"[[Diesel required for 594 km = 108 litres, Die...",Concept of Unitary Method,Exp0675
676,6,12,Ratio and Proportion,12.3,Q 10.,[Raju purchases 10 pens for Rs 150 and Manish ...,"[[Raju purchased 10 pens for Rs 150., ∴ Price ...",Concept of Unitary Method,Exp0676
677,6,12,Ratio and Proportion,12.3,Q 11.,[Anish made 42 runs in 6 overs and Anup made 6...,"[[Runs made by Anish in 6 overs = 42, ∴ Runs m...",Concept of Unitary Method,Exp0677

In [6]:
"\n".join(var_df.problem[0])

'Write the next three natural numbers after 10999.'

In [7]:
sols = ""
for idx, sol in enumerate(var_df.solution[0] + var_df.solution[0], start=1):
    sols += f"Sol {idx}:\n" + "\n".join(sol) + "\n\n"

print(sols[:-2])

Sol 1:
10,999+1 = 11,000
11,000 + 1 = 11,001
11,001 + 1 = 11,002
∴ The next three natural numbers after 10,999 are 11,000; 11,001; 11,002

Sol 2:
10,999+1 = 11,000
11,000 + 1 = 11,001
11,001 + 1 = 11,002
∴ The next three natural numbers after 10,999 are 11,000; 11,001; 11,002

In [8]:
input_text = input_prompt.format(math_problem="\n".join(var_df.problem[0]), solution=sols[:-2])
print(input_text)

<math_problem>
Write the next three natural numbers after 10999.
</math_problem>

<solution>
Sol 1:
10,999+1 = 11,000
11,000 + 1 = 11,001
11,001 + 1 = 11,002
∴ The next three natural numbers after 10,999 are 11,000; 11,001; 11,002

Sol 2:
10,999+1 = 11,000
11,000 + 1 = 11,001
11,001 + 1 = 11,002
∴ The next three natural numbers after 10,999 are 11,000; 11,001; 11,002
</solution>

In [9]:
exp_id = 0
jsonl_fnames = [f'cleaned_class_{class_num}.jsonl' for class_num in range(6, 13)]
ids = []
problems = []
solutions = []
prompt = []
concepts = []
chapter_names = []

for jsonl_fname in jsonl_fnames:
    var_df = pd.read_json(os.path.join(BASE_FOLDER, jsonl_fname), lines=True)
    for idx in tqdm(range(len(var_df))):
        prob = "\n".join(var_df.problem[idx])
        sols = ""
        for sol in var_df.solution[idx]:
            sols += "\n".join(sol) + "\n\n"
        sols = sols[:-2]
        input_text = input_prompt.format(math_problem=prob, solution=sols)
        
        ids.append(f"Exp{exp_id:0>4}")
        problems.append(prob)
        solutions.append(sols)
        prompt.append(input_text)
        concepts.append(var_df.concept[idx])
        chapter_names.append(var_df.chapter_name[idx])

        var_df.loc[idx, 'exp_id'] = f"Exp{exp_id:0>4}"
        exp_id += 1
    
    # var_df.to_json(os.path.join(BASE_FOLDER, jsonl_fname), index=False, lines=True, orient='records')

  0%|          | 0/678 [00:00<?, ?it/s]

  0%|          | 0/699 [00:00<?, ?it/s]

  0%|          | 0/547 [00:00<?, ?it/s]

  0%|          | 0/311 [00:00<?, ?it/s]

  0%|          | 0/506 [00:00<?, ?it/s]

  0%|          | 0/698 [00:00<?, ?it/s]

  0%|          | 0/887 [00:00<?, ?it/s]

In [11]:
preprocess_df = pd.DataFrame({
    "id": ids,
    "problem": problems,
    "solution": solutions,
    "prompt": prompt,
    "concept": concepts,
    "chapter_name": chapter_names
})
preprocess_df

,id,problem,solution,prompt,concept,chapter_name
0,Exp0000,Write the next three natural numbers after 10999.,"10,999+1 = 11,000\n11,000 + 1 = 11,001\n11,001...",<math_problem>\nWrite the next three natural n...,Concept for Natural Numbers,Whole Numbers
1,Exp0001,Write the three whole numbers occurring just b...,Three whole numbers occurring just before 1000...,<math_problem>\nWrite the three whole numbers ...,Concept for Whole Numbers,Whole Numbers
2,Exp0002,Which is the smallest whole number?,0 (zero) is the smallest whole number. All the...,<math_problem>\nWhich is the smallest whole nu...,Concept for Whole Numbers,Whole Numbers
3,Exp0003,How many whole numbers are there between 32 an...,Whole numbers between 32 and 53 = 20 (53 − 32 ...,<math_problem>\nHow many whole numbers are the...,Concept for Whole Numbers,Whole Numbers
4,Exp0004,Write the successor of 2440701.,The successor of 2440701 is\n2440701 + 1 = 244...,<math_problem>\nWrite the successor of 2440701...,Successor and Predecessor of Whole Number,Whole Numbers
...,...,...,...,...,...,...
4321,Exp4321,If each element of a second order determinant ...,The total number of determinants of second ord...,<math_problem>\nIf each element of a second or...,Independent Events,Probability
4322,Exp4322,An electronic assembly consists of two subsyst...,Let the event in which A fails and B fails be ...,<math_problem>\nAn electronic assembly consist...,Properties of Conditional Probability,Probability
4323,Exp4323,If A and B are two events such that P (A) ≠ 0 ...,"P (A) ≠ 0 and P(B|A) = 1\n\nThus, the correct ...",<math_problem>\nIf A and B are two events such...,Properties of Conditional Probability,Probability
4324,Exp4324,"If P (A|B) > P (A), then which of the followin...","\nThus, the correct answer is C.","<math_problem>\nIf P (A|B) > P (A), then which...",Properties of Conditional Probability,Probability
4325,Exp4325,If A and B are any two events such that P (A) ...,"\nThus, the correct answer is B.",<math_problem>\nIf A and B are any two events ...,Properties of Conditional Probability,Probability

In [12]:
preprocess_df.to_json(os.path.join(BASE_FOLDER, 'preprocess_input.jsonl'), index=False, lines=True, orient='records')

In [13]:
preprocess_df.concept.nunique()

411